### ISSUE TITLE
assigment2 problem?

### ISSUE THREAD

**Issue by HadXu** [dlsys-course/assignment2-2018#1]
when I change `tgt="llvm"` to `tgt='cuda'`,and I run `make_elemwise_add()`,I have an error

`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/amax/.local/lib/python3.6/site-packages/tvm-0.2.0-py3.6-linux-x86_64.egg/tvm/build_module.py", line 452, in build
    "Did you forget to bind?" % func.name)
ValueError: Direct host side access to device memory is detected in add. Did you forget to bind?`

so, when I run on gpu,need to set `bind`? if `bind` is required,I think TVM is not so simple? thanks

**Comment by tqchen** [comment]
yes, we would need explicit gpu schedules(binds) to make things run on gpu
